#Region "Code"
Imports System.IO
Public Class Form1
    Private Sub load_card_Click(sender As Object, e As EventArgs) Handles load_card.Click
        If file_open.ShowDialog = Windows.Forms.DialogResult.OK Then
            Dim file_find As FileStream = File.OpenRead(file_open.FileName)
            Dim file_read As New BinaryReader(file_find)
            Dim wondercard(&HCC) As Byte
            wondercard = file_read.ReadBytes(&HCC)
            file_find.Seek(&H60, SeekOrigin.Begin)
            Dim title_bytes(&H4A) As Byte
            title_bytes = file_read.ReadBytes(&H4A)
            Dim title_reader As New System.Text.UnicodeEncoding()
            Dim card_title As String = title_reader.GetString(title_bytes, 0, &H4A)
            Me.Text = BitConverter.ToUInt16(wondercard, &HB0) & " - " & card_title
            Dim pokedexnum As UInt16 = BitConverter.ToUInt16(wondercard, &H1A)
            Label1.Text = PokeLib.ReturnName(pokedexnum)
            PictureBox1.Image = PokeLib.ReturnSprite(pokedexnum)
            Label2.Text = PokeLib.ReturnShininess(wondercard(&H37))
            Label5.Text = PokeLib.ReturnLocation(BitConverter.ToUInt16(wondercard, &H38))
            Label6.Text = PokeLib.ReturnLocation(BitConverter.ToUInt16(wondercard, &H3A))
            Label8.Text = PokeLib.ReturnHometown(wondercard(&H4))
            Label16.Text = PokeLib.ReturnGender(wondercard(&H35))
            Label18.Text = PokeLib.ReturnOTGender(wondercard(&H5A))
            Label21.Text = BitConverter.ToUInt16(wondercard, 0)
            Label22.Text = BitConverter.ToUInt16(wondercard, 2)
            If Label21.Text = "0" Then
                Label21.Text = "0 / Trainer's ID"
            Else
                Label21.Text = Label21.Text
            End If
            Label24.Text = PokeLib.ReturnCTypeName(wondercard(&HB3))
            Label24.ForeColor = PokeLib.ReturnCTypeColor(wondercard(&HB3))
            file_read.Close()
            file_find.Close()
        End If
    End Sub
End Class
Public Class PokeLib
#Region "Dictionary"
#Region "Declarations"
    Private Shared mDicInit As Boolean = False
    Public Shared dPKMSpecies As New Dictionary(Of UInt16, String)
    Public Shared PicLibrary As New Dictionary(Of UInt16, Image)
    Public Shared bwLocations As New Dictionary(Of UInt16, String)
    Public Shared hometowns As New Dictionary(Of Byte, String)
    Public Shared genders As New Dictionary(Of Byte, String)
    Public Shared ot_genders As New Dictionary(Of Byte, String)
    Public Shared ctype_name As New Dictionary(Of Byte, String)
    Public Shared ctype_color As New Dictionary(Of Byte, Color)
#End Region
    Public Shared Sub DicInit()
        If mDicInit Then Exit Sub
        dPKMSpecies.Add(0, "MissingNO.")
        dPKMSpecies.Add(1, "Bulbasaur")
        dPKMSpecies.Add(2, "Ivysaur")
        dPKMSpecies.Add(3, "Venusaur")
        dPKMSpecies.Add(4, "Charmander")
        dPKMSpecies.Add(5, "Charmeleon")
        dPKMSpecies.Add(6, "Charizard")
        dPKMSpecies.Add(7, "Squirtle")
        dPKMSpecies.Add(8, "Wartortle")
        dPKMSpecies.Add(9, "Blastoise")
        dPKMSpecies.Add(10, "Caterpie")
        dPKMSpecies.Add(11, "Metapod")
        dPKMSpecies.Add(12, "Butterfree")
        dPKMSpecies.Add(13, "Weedle")
        dPKMSpecies.Add(14, "Kakuna")
        dPKMSpecies.Add(15, "Beedrill")
        dPKMSpecies.Add(16, "Pidgey")
        dPKMSpecies.Add(17, "Pidgeotto")
        dPKMSpecies.Add(18, "Pidgeot")
        dPKMSpecies.Add(19, "Rattata")
        dPKMSpecies.Add(20, "Raticate")
        dPKMSpecies.Add(21, "Spearow")
        dPKMSpecies.Add(22, "Fearow")
        dPKMSpecies.Add(23, "Ekans")
        dPKMSpecies.Add(24, "Arbok")
        dPKMSpecies.Add(25, "Pikachu")
        dPKMSpecies.Add(26, "Raichu")
        dPKMSpecies.Add(27, "Sandshrew")
        dPKMSpecies.Add(28, "Sandslash")
        dPKMSpecies.Add(29, "Nidoran" & Char.ConvertFromUtf32(&H1BC))
        dPKMSpecies.Add(30, "Nidorina")
        dPKMSpecies.Add(31, "Nidoqueen")
        dPKMSpecies.Add(32, "Nidoran" & Char.ConvertFromUtf32(&H1BB))
        dPKMSpecies.Add(33, "Nidorino")
        dPKMSpecies.Add(34, "Nidoking")
        dPKMSpecies.Add(35, "Clefairy")
        dPKMSpecies.Add(36, "Clefable")
        dPKMSpecies.Add(37, "Vulpix")
        dPKMSpecies.Add(38, "Ninetales")
        dPKMSpecies.Add(39, "Jigglypuff")
        dPKMSpecies.Add(40, "Wigglytuff")
        dPKMSpecies.Add(41, "Zubat")
        dPKMSpecies.Add(42, "Golbat")
        dPKMSpecies.Add(43, "Oddish")
        dPKMSpecies.Add(44, "Gloom")
        dPKMSpecies.Add(45, "Vileplume")
        dPKMSpecies.Add(46, "Paras")
        dPKMSpecies.Add(47, "Parasect")
        dPKMSpecies.Add(48, "Venonat")
        dPKMSpecies.Add(49, "Venomoth")
        dPKMSpecies.Add(50, "Diglett")
        dPKMSpecies.Add(51, "Dugtrio")
        dPKMSpecies.Add(52, "Meowth")
        dPKMSpecies.Add(53, "Persian")
        dPKMSpecies.Add(54, "Psyduck")
        dPKMSpecies.Add(55, "Golduck")
        dPKMSpecies.Add(56, "Mankey")
        dPKMSpecies.Add(57, "Primeape")
        dPKMSpecies.Add(58, "Growlithe")
        dPKMSpecies.Add(59, "Arcanine")
        dPKMSpecies.Add(60, "Poliwag")
        dPKMSpecies.Add(61, "Poliwhirl")
        dPKMSpecies.Add(62, "Poliwrath")
        dPKMSpecies.Add(63, "Abra")
        dPKMSpecies.Add(64, "Kadabra")
        dPKMSpecies.Add(65, "Alakazam")
        dPKMSpecies.Add(66, "Machop")
        dPKMSpecies.Add(67, "Machoke")
        dPKMSpecies.Add(68, "Machamp")
        dPKMSpecies.Add(69, "Bellsprout")
        dPKMSpecies.Add(70, "Weepinbell")
        dPKMSpecies.Add(71, "Victreebel")
        dPKMSpecies.Add(72, "Tentacool")
        dPKMSpecies.Add(73, "Tentacruel")
        dPKMSpecies.Add(74, "Geodude")
        dPKMSpecies.Add(75, "Graveler")
        dPKMSpecies.Add(76, "Golem")
        dPKMSpecies.Add(77, "Ponyta")
        dPKMSpecies.Add(78, "Rapidash")
        dPKMSpecies.Add(79, "Slowpoke")
        dPKMSpecies.Add(80, "Slowbro")
        dPKMSpecies.Add(81, "Magnemite")
        dPKMSpecies.Add(82, "Magneton")
        dPKMSpecies.Add(83, "Farfetch'd")
        dPKMSpecies.Add(84, "Doduo")
        dPKMSpecies.Add(85, "Dodrio")
        dPKMSpecies.Add(86, "Seel")
        dPKMSpecies.Add(87, "Dewgong")
        dPKMSpecies.Add(88, "Grimer")
        dPKMSpecies.Add(89, "Muk")
        dPKMSpecies.Add(90, "Shellder")
        dPKMSpecies.Add(91, "Cloyster")
        dPKMSpecies.Add(92, "Gastly")
        dPKMSpecies.Add(93, "Haunter")
        dPKMSpecies.Add(94, "Gengar")
        dPKMSpecies.Add(95, "Onix")
        dPKMSpecies.Add(96, "Drowzee")
        dPKMSpecies.Add(97, "Hypno")
        dPKMSpecies.Add(98, "Krabby")
        dPKMSpecies.Add(99, "Kingler")
        dPKMSpecies.Add(100, "Voltorb")
        dPKMSpecies.Add(101, "Electrode")
        dPKMSpecies.Add(102, "Exeggcute")
        dPKMSpecies.Add(103, "Exeggutor")
        dPKMSpecies.Add(104, "Cubone")
        dPKMSpecies.Add(105, "Marowak")
        dPKMSpecies.Add(106, "Hitmonlee")
        dPKMSpecies.Add(107, "Hitmonchan")
        dPKMSpecies.Add(108, "Lickitung")
        dPKMSpecies.Add(109, "Koffing")
        dPKMSpecies.Add(110, "Weezing")
        dPKMSpecies.Add(111, "Rhyhorn")
        dPKMSpecies.Add(112, "Rhydon")
        dPKMSpecies.Add(113, "Chansey")
        dPKMSpecies.Add(114, "Tangela")
        dPKMSpecies.Add(115, "Kangaskhan")
        dPKMSpecies.Add(116, "Horsea")
        dPKMSpecies.Add(117, "Seadra")
        dPKMSpecies.Add(118, "Goldeen")
        dPKMSpecies.Add(119, "Seaking")
        dPKMSpecies.Add(120, "Staryu")
        dPKMSpecies.Add(121, "Starmie")
        dPKMSpecies.Add(122, "Mr. Mime")
        dPKMSpecies.Add(123, "Scyther")
        dPKMSpecies.Add(124, "Jynx")
        dPKMSpecies.Add(125, "Electabuzz")
        dPKMSpecies.Add(126, "Magmar")
        dPKMSpecies.Add(127, "Pinsir")
        dPKMSpecies.Add(128, "Tauros")
        dPKMSpecies.Add(129, "Magikarp")
        dPKMSpecies.Add(130, "Gyarados")
        dPKMSpecies.Add(131, "Lapras")
        dPKMSpecies.Add(132, "Ditto")
        dPKMSpecies.Add(133, "Eevee")
        dPKMSpecies.Add(134, "Vaporeon")
        dPKMSpecies.Add(135, "Jolteon")
        dPKMSpecies.Add(136, "Flareon")
        dPKMSpecies.Add(137, "Porygon")
        dPKMSpecies.Add(138, "Omanyte")
        dPKMSpecies.Add(139, "Omastar")
        dPKMSpecies.Add(140, "Kabuto")
        dPKMSpecies.Add(141, "Kabutops")
        dPKMSpecies.Add(142, "Aerodactyl")
        dPKMSpecies.Add(143, "Snorlax")
        dPKMSpecies.Add(144, "Articuno")
        dPKMSpecies.Add(145, "Zapdos")
        dPKMSpecies.Add(146, "Moltres")
        dPKMSpecies.Add(147, "Dratini")
        dPKMSpecies.Add(148, "Dragonair")
        dPKMSpecies.Add(149, "Dragonite")
        dPKMSpecies.Add(150, "Mewtwo")
        dPKMSpecies.Add(151, "Mew")
        dPKMSpecies.Add(152, "Chikorita")
        dPKMSpecies.Add(153, "Bayleef")
        dPKMSpecies.Add(154, "Meganium")
        dPKMSpecies.Add(155, "Cyndaquil")
        dPKMSpecies.Add(156, "Quilava")
        dPKMSpecies.Add(157, "Typhlosion")
        dPKMSpecies.Add(158, "Totodile")
        dPKMSpecies.Add(159, "Croconaw")
        dPKMSpecies.Add(160, "Feraligatr")
        dPKMSpecies.Add(161, "Sentret")
        dPKMSpecies.Add(162, "Furret")
        dPKMSpecies.Add(163, "Hoothoot")
        dPKMSpecies.Add(164, "Noctowl")
        dPKMSpecies.Add(165, "Ledyba")
        dPKMSpecies.Add(166, "Ledian")
        dPKMSpecies.Add(167, "Spinarak")
        dPKMSpecies.Add(168, "Ariados")
        dPKMSpecies.Add(169, "Crobat")
        dPKMSpecies.Add(170, "Chinchou")
        dPKMSpecies.Add(171, "Lanturn")
        dPKMSpecies.Add(172, "Pichu")
        dPKMSpecies.Add(173, "Cleffa")
        dPKMSpecies.Add(174, "Igglybuff")
        dPKMSpecies.Add(175, "Togepi")
        dPKMSpecies.Add(176, "Togetic")
        dPKMSpecies.Add(177, "Natu")
        dPKMSpecies.Add(178, "Xatu")
        dPKMSpecies.Add(179, "Mareep")
        dPKMSpecies.Add(180, "Flaaffy")
        dPKMSpecies.Add(181, "Ampharos")
        dPKMSpecies.Add(182, "Bellossom")
        dPKMSpecies.Add(183, "Marill")
        dPKMSpecies.Add(184, "Azumarill")
        dPKMSpecies.Add(185, "Sudowoodo")
        dPKMSpecies.Add(186, "Politoed")
        dPKMSpecies.Add(187, "Hoppip")
        dPKMSpecies.Add(188, "Skiploom")
        dPKMSpecies.Add(189, "Jumpluff")
        dPKMSpecies.Add(190, "Aipom")
        dPKMSpecies.Add(191, "Sunkern")
        dPKMSpecies.Add(192, "Sunflora")
        dPKMSpecies.Add(193, "Yanma")
        dPKMSpecies.Add(194, "Wooper")
        dPKMSpecies.Add(195, "Quagsire")
        dPKMSpecies.Add(196, "Espeon")
        dPKMSpecies.Add(197, "Umbreon")
        dPKMSpecies.Add(198, "Murkrow")
        dPKMSpecies.Add(199, "Slowking")
        dPKMSpecies.Add(200, "Misdreavus")
        dPKMSpecies.Add(201, "Unown")
        dPKMSpecies.Add(202, "Wobbuffet")
        dPKMSpecies.Add(203, "Girafarig")
        dPKMSpecies.Add(204, "Pineco")
        dPKMSpecies.Add(205, "Forretress")
        dPKMSpecies.Add(206, "Dunsparce")
        dPKMSpecies.Add(207, "Gligar")
        dPKMSpecies.Add(208, "Steelix")
        dPKMSpecies.Add(209, "Snubbull")
        dPKMSpecies.Add(210, "Granbull")
        dPKMSpecies.Add(211, "Qwilfish")
        dPKMSpecies.Add(212, "Scizor")
        dPKMSpecies.Add(213, "Shuckle")
        dPKMSpecies.Add(214, "Heracross")
        dPKMSpecies.Add(215, "Sneasel")
        dPKMSpecies.Add(216, "Teddiursa")
        dPKMSpecies.Add(217, "Ursaring")
        dPKMSpecies.Add(218, "Slugma")
        dPKMSpecies.Add(219, "Magcargo")
        dPKMSpecies.Add(220, "Swinub")
        dPKMSpecies.Add(221, "Piloswine")
        dPKMSpecies.Add(222, "Corsola")
        dPKMSpecies.Add(223, "Remoraid")
        dPKMSpecies.Add(224, "Octillery")
        dPKMSpecies.Add(225, "Delibird")
        dPKMSpecies.Add(226, "Mantine")
        dPKMSpecies.Add(227, "Skarmory")
        dPKMSpecies.Add(228, "Houndour")
        dPKMSpecies.Add(229, "Houndoom")
        dPKMSpecies.Add(230, "Kingdra")
        dPKMSpecies.Add(231, "Phanpy")
        dPKMSpecies.Add(232, "Donphan")
        dPKMSpecies.Add(233, "Porygon2")
        dPKMSpecies.Add(234, "Stantler")
        dPKMSpecies.Add(235, "Smeargle")
        dPKMSpecies.Add(236, "Tyrogue")
        dPKMSpecies.Add(237, "Hitmontop")
        dPKMSpecies.Add(238, "Smoochum")
        dPKMSpecies.Add(239, "Elekid")
        dPKMSpecies.Add(240, "Magby")
        dPKMSpecies.Add(241, "Miltank")
        dPKMSpecies.Add(242, "Blissey")
        dPKMSpecies.Add(243, "Raikou")
        dPKMSpecies.Add(244, "Entei")
        dPKMSpecies.Add(245, "Suicune")
        dPKMSpecies.Add(246, "Larvitar")
        dPKMSpecies.Add(247, "Pupitar")
        dPKMSpecies.Add(248, "Tyranitar")
        dPKMSpecies.Add(249, "Lugia")
        dPKMSpecies.Add(250, "Ho-Oh")
        dPKMSpecies.Add(251, "Celebi")
        dPKMSpecies.Add(252, "Treecko")
        dPKMSpecies.Add(253, "Grovyle")
        dPKMSpecies.Add(254, "Sceptile")
        dPKMSpecies.Add(255, "Torchic")
        dPKMSpecies.Add(256, "Combusken")
        dPKMSpecies.Add(257, "Blaziken")
        dPKMSpecies.Add(258, "Mudkip")
        dPKMSpecies.Add(259, "Marshtomp")
        dPKMSpecies.Add(260, "Swampert")
        dPKMSpecies.Add(261, "Poochyena")
        dPKMSpecies.Add(262, "Mightyena")
        dPKMSpecies.Add(263, "Zigzagoon")
        dPKMSpecies.Add(264, "Linoone")
        dPKMSpecies.Add(265, "Wurmple")
        dPKMSpecies.Add(266, "Silcoon")
        dPKMSpecies.Add(267, "Beautifly")
        dPKMSpecies.Add(268, "Cascoon")
        dPKMSpecies.Add(269, "Dustox")
        dPKMSpecies.Add(270, "Lotad")
        dPKMSpecies.Add(271, "Lombre")
        dPKMSpecies.Add(272, "Ludicolo")
        dPKMSpecies.Add(273, "Seedot")
        dPKMSpecies.Add(274, "Nuzleaf")
        dPKMSpecies.Add(275, "Shiftry")
        dPKMSpecies.Add(276, "Taillow")
        dPKMSpecies.Add(277, "Swellow")
        dPKMSpecies.Add(278, "Wingull")
        dPKMSpecies.Add(279, "Pelipper")
        dPKMSpecies.Add(280, "Ralts")
        dPKMSpecies.Add(281, "Kirlia")
        dPKMSpecies.Add(282, "Gardevoir")
        dPKMSpecies.Add(283, "Surskit")
        dPKMSpecies.Add(284, "Masquerain")
        dPKMSpecies.Add(285, "Shroomish")
        dPKMSpecies.Add(286, "Breloom")
        dPKMSpecies.Add(287, "Slakoth")
        dPKMSpecies.Add(288, "Vigoroth")
        dPKMSpecies.Add(289, "Slaking")
        dPKMSpecies.Add(290, "Nincada")
        dPKMSpecies.Add(291, "Ninjask")
        dPKMSpecies.Add(292, "Shedinja")
        dPKMSpecies.Add(293, "Whismur")
        dPKMSpecies.Add(294, "Loudred")
        dPKMSpecies.Add(295, "Exploud")
        dPKMSpecies.Add(296, "Makuhita")
        dPKMSpecies.Add(297, "Hariyama")
        dPKMSpecies.Add(298, "Azurill")
        dPKMSpecies.Add(299, "Nosepass")
        dPKMSpecies.Add(300, "Skitty")
        dPKMSpecies.Add(301, "Delcatty")
        dPKMSpecies.Add(302, "Sableye")
        dPKMSpecies.Add(303, "Mawile")
        dPKMSpecies.Add(304, "Aron")
        dPKMSpecies.Add(305, "Lairon")
        dPKMSpecies.Add(306, "Aggron")
        dPKMSpecies.Add(307, "Meditite")
        dPKMSpecies.Add(308, "Medicham")
        dPKMSpecies.Add(309, "Electrike")
        dPKMSpecies.Add(310, "Manectric")
        dPKMSpecies.Add(311, "Plusle")
        dPKMSpecies.Add(312, "Minun")
        dPKMSpecies.Add(313, "Volbeat")
        dPKMSpecies.Add(314, "Illumise")
        dPKMSpecies.Add(315, "Roselia")
        dPKMSpecies.Add(316, "Gulpin")
        dPKMSpecies.Add(317, "Swalot")
        dPKMSpecies.Add(318, "Carvanha")
        dPKMSpecies.Add(319, "Sharpedo")
        dPKMSpecies.Add(320, "Wailmer")
        dPKMSpecies.Add(321, "Wailord")
        dPKMSpecies.Add(322, "Numel")
        dPKMSpecies.Add(323, "Camerupt")
        dPKMSpecies.Add(324, "Torkoal")
        dPKMSpecies.Add(325, "Spoink")
        dPKMSpecies.Add(326, "Grumpig")
        dPKMSpecies.Add(327, "Spinda")
        dPKMSpecies.Add(328, "Trapinch")
        dPKMSpecies.Add(329, "Vibrava")
        dPKMSpecies.Add(330, "Flygon")
        dPKMSpecies.Add(331, "Cacnea")
        dPKMSpecies.Add(332, "Cacturne")
        dPKMSpecies.Add(333, "Swablu")
        dPKMSpecies.Add(334, "Altaria")
        dPKMSpecies.Add(335, "Zangoose")
        dPKMSpecies.Add(336, "Seviper")
        dPKMSpecies.Add(337, "Lunatone")
        dPKMSpecies.Add(338, "Solrock")
        dPKMSpecies.Add(339, "Barboach")
        dPKMSpecies.Add(340, "Whiscash")
        dPKMSpecies.Add(341, "Corphish")
        dPKMSpecies.Add(342, "Crawdaunt")
        dPKMSpecies.Add(343, "Baltoy")
        dPKMSpecies.Add(344, "Claydol")
        dPKMSpecies.Add(345, "Lileep")
        dPKMSpecies.Add(346, "Cradily")
        dPKMSpecies.Add(347, "Anorith")
        dPKMSpecies.Add(348, "Armaldo")
        dPKMSpecies.Add(349, "Feebas")
        dPKMSpecies.Add(350, "Milotic")
        dPKMSpecies.Add(351, "Castform")
        dPKMSpecies.Add(352, "Kecleon")
        dPKMSpecies.Add(353, "Shuppet")
        dPKMSpecies.Add(354, "Banette")
        dPKMSpecies.Add(355, "Duskull")
        dPKMSpecies.Add(356, "Dusclops")
        dPKMSpecies.Add(357, "Tropius")
        dPKMSpecies.Add(358, "Chimecho")
        dPKMSpecies.Add(359, "Absol")
        dPKMSpecies.Add(360, "Wynaut")
        dPKMSpecies.Add(361, "Snorunt")
        dPKMSpecies.Add(362, "Glalie")
        dPKMSpecies.Add(363, "Spheal")
        dPKMSpecies.Add(364, "Sealeo")
        dPKMSpecies.Add(365, "Walrein")
        dPKMSpecies.Add(366, "Clamperl")
        dPKMSpecies.Add(367, "Huntail")
        dPKMSpecies.Add(368, "Gorebyss")
        dPKMSpecies.Add(369, "Relicanth")
        dPKMSpecies.Add(370, "Luvdisc")
        dPKMSpecies.Add(371, "Bagon")
        dPKMSpecies.Add(372, "Shelgon")
        dPKMSpecies.Add(373, "Salamence")
        dPKMSpecies.Add(374, "Beldum")
        dPKMSpecies.Add(375, "Metang")
        dPKMSpecies.Add(376, "Metagross")
        dPKMSpecies.Add(377, "Regirock")
        dPKMSpecies.Add(378, "Regice")
        dPKMSpecies.Add(379, "Registeel")
        dPKMSpecies.Add(380, "Latias")
        dPKMSpecies.Add(381, "Latios")
        dPKMSpecies.Add(382, "Kyogre")
        dPKMSpecies.Add(383, "Groudon")
        dPKMSpecies.Add(384, "Rayquaza")
        dPKMSpecies.Add(385, "Jirachi")
        dPKMSpecies.Add(386, "Deoxys")
        dPKMSpecies.Add(387, "Turtwig")
        dPKMSpecies.Add(388, "Grotle")
        dPKMSpecies.Add(389, "Torterra")
        dPKMSpecies.Add(390, "Chimchar")
        dPKMSpecies.Add(391, "Monferno")
        dPKMSpecies.Add(392, "Infernape")
        dPKMSpecies.Add(393, "Piplup")
        dPKMSpecies.Add(394, "Prinplup")
        dPKMSpecies.Add(395, "Empoleon")
        dPKMSpecies.Add(396, "Starly")
        dPKMSpecies.Add(397, "Staravia")
        dPKMSpecies.Add(398, "Staraptor")
        dPKMSpecies.Add(399, "Bidoof")
        dPKMSpecies.Add(400, "Bibarel")
        dPKMSpecies.Add(401, "Kricketot")
        dPKMSpecies.Add(402, "Kricketune")
        dPKMSpecies.Add(403, "Shinx")
        dPKMSpecies.Add(404, "Luxio")
        dPKMSpecies.Add(405, "Luxray")
        dPKMSpecies.Add(406, "Budew")
        dPKMSpecies.Add(407, "Roserade")
        dPKMSpecies.Add(408, "Cranidos")
        dPKMSpecies.Add(409, "Rampardos")
        dPKMSpecies.Add(410, "Shieldon")
        dPKMSpecies.Add(411, "Bastiodon")
        dPKMSpecies.Add(412, "Burmy")
        dPKMSpecies.Add(413, "Wormadam")
        dPKMSpecies.Add(414, "Mothim")
        dPKMSpecies.Add(415, "Combee")
        dPKMSpecies.Add(416, "Vespiquen")
        dPKMSpecies.Add(417, "Pachirisu")
        dPKMSpecies.Add(418, "Buizel")
        dPKMSpecies.Add(419, "Floatzel")
        dPKMSpecies.Add(420, "Cherubi")
        dPKMSpecies.Add(421, "Cherrim")
        dPKMSpecies.Add(422, "Shellos")
        dPKMSpecies.Add(423, "Gastrodon")
        dPKMSpecies.Add(424, "Ambipom")
        dPKMSpecies.Add(425, "Drifloon")
        dPKMSpecies.Add(426, "Drifblim")
        dPKMSpecies.Add(427, "Buneary")
        dPKMSpecies.Add(428, "Lopunny")
        dPKMSpecies.Add(429, "Mismagius")
        dPKMSpecies.Add(430, "Honchkrow")
        dPKMSpecies.Add(431, "Glameow")
        dPKMSpecies.Add(432, "Purugly")
        dPKMSpecies.Add(433, "Chingling")
        dPKMSpecies.Add(434, "Stunky")
        dPKMSpecies.Add(435, "Skuntank")
        dPKMSpecies.Add(436, "Bronzor")
        dPKMSpecies.Add(437, "Bronzong")
        dPKMSpecies.Add(438, "Bonsly")
        dPKMSpecies.Add(439, "Mime Jr.")
        dPKMSpecies.Add(440, "Happiny")
        dPKMSpecies.Add(441, "Chatot")
        dPKMSpecies.Add(442, "Spiritomb")
        dPKMSpecies.Add(443, "Gible")
        dPKMSpecies.Add(444, "Gabite")
        dPKMSpecies.Add(445, "Garchomp")
        dPKMSpecies.Add(446, "Munchlax")
        dPKMSpecies.Add(447, "Riolu")
        dPKMSpecies.Add(448, "Lucario")
        dPKMSpecies.Add(449, "Hippopotas")
        dPKMSpecies.Add(450, "Hippowdon")
        dPKMSpecies.Add(451, "Skorupi")
        dPKMSpecies.Add(452, "Drapion")
        dPKMSpecies.Add(453, "Croagunk")
        dPKMSpecies.Add(454, "Toxicroak")
        dPKMSpecies.Add(455, "Carnivine")
        dPKMSpecies.Add(456, "Finneon")
        dPKMSpecies.Add(457, "Lumineon")
        dPKMSpecies.Add(458, "Mantyke")
        dPKMSpecies.Add(459, "Snover")
        dPKMSpecies.Add(460, "Abomasnow")
        dPKMSpecies.Add(461, "Weavile")
        dPKMSpecies.Add(462, "Magnezone")
        dPKMSpecies.Add(463, "Lickilicky")
        dPKMSpecies.Add(464, "Rhyperior")
        dPKMSpecies.Add(465, "Tangrowth")
        dPKMSpecies.Add(466, "Electivire")
        dPKMSpecies.Add(467, "Magmortar")
        dPKMSpecies.Add(468, "Togekiss")
        dPKMSpecies.Add(469, "Yanmega")
        dPKMSpecies.Add(470, "Leafeon")
        dPKMSpecies.Add(471, "Glaceon")
        dPKMSpecies.Add(472, "Gliscor")
        dPKMSpecies.Add(473, "Mamoswine")
        dPKMSpecies.Add(474, "Porygon-Z")
        dPKMSpecies.Add(475, "Gallade")
        dPKMSpecies.Add(476, "Probopass")
        dPKMSpecies.Add(477, "Dusknoir")
        dPKMSpecies.Add(478, "Froslass")
        dPKMSpecies.Add(479, "Rotom")
        dPKMSpecies.Add(480, "Uxie")
        dPKMSpecies.Add(481, "Mesprit")
        dPKMSpecies.Add(482, "Azelf")
        dPKMSpecies.Add(483, "Dialga")
        dPKMSpecies.Add(484, "Palkia")
        dPKMSpecies.Add(485, "Heatran")
        dPKMSpecies.Add(486, "Regigigas")
        dPKMSpecies.Add(487, "Giratina")
        dPKMSpecies.Add(488, "Cresselia")
        dPKMSpecies.Add(489, "Phione")
        dPKMSpecies.Add(490, "Manaphy")
        dPKMSpecies.Add(491, "Darkrai")
        dPKMSpecies.Add(492, "Shaymin")
        dPKMSpecies.Add(493, "Arceus")
        dPKMSpecies.Add(494, "Victini")
        dPKMSpecies.Add(495, "Snivy")
        dPKMSpecies.Add(496, "Servine")
        dPKMSpecies.Add(497, "Serperior")
        dPKMSpecies.Add(498, "Tepig")
        dPKMSpecies.Add(499, "Pignite")
        dPKMSpecies.Add(500, "Emboar")
        dPKMSpecies.Add(501, "Oshawott")
        dPKMSpecies.Add(502, "Dewott")
        dPKMSpecies.Add(503, "Samurott")
        dPKMSpecies.Add(504, "Patrat")
        dPKMSpecies.Add(505, "Watchog")
        dPKMSpecies.Add(506, "Lillipup")
        dPKMSpecies.Add(507, "Herdier")
        dPKMSpecies.Add(508, "Stoutland")
        dPKMSpecies.Add(509, "Purrloin")
        dPKMSpecies.Add(510, "Liepard")
        dPKMSpecies.Add(511, "Pansage")
        dPKMSpecies.Add(512, "Simisage")
        dPKMSpecies.Add(513, "Pansear")
        dPKMSpecies.Add(514, "Simisear")
        dPKMSpecies.Add(515, "Panpour")
        dPKMSpecies.Add(516, "Simipour")
        dPKMSpecies.Add(517, "Munna")
        dPKMSpecies.Add(518, "Musharna")
        dPKMSpecies.Add(519, "Pidove")
        dPKMSpecies.Add(520, "Tranquill")
        dPKMSpecies.Add(521, "Unfezant")
        dPKMSpecies.Add(522, "Blitzle")
        dPKMSpecies.Add(523, "Zebstrika")
        dPKMSpecies.Add(524, "Roggenrola")
        dPKMSpecies.Add(525, "Boldore")
        dPKMSpecies.Add(526, "Gigalith")
        dPKMSpecies.Add(527, "Woobat")
        dPKMSpecies.Add(528, "Swoobat")
        dPKMSpecies.Add(529, "Drilbur")
        dPKMSpecies.Add(530, "Excadrill")
        dPKMSpecies.Add(531, "Audino")
        dPKMSpecies.Add(532, "Timburr")
        dPKMSpecies.Add(533, "Gurdurr")
        dPKMSpecies.Add(534, "Conkeldurr")
        dPKMSpecies.Add(535, "Tympole")
        dPKMSpecies.Add(536, "Palpitoad")
        dPKMSpecies.Add(537, "Seismitoad")
        dPKMSpecies.Add(538, "Throh")
        dPKMSpecies.Add(539, "Sawk")
        dPKMSpecies.Add(540, "Sewaddle")
        dPKMSpecies.Add(541, "Swadloon")
        dPKMSpecies.Add(542, "Leavanny")
        dPKMSpecies.Add(543, "Venipede")
        dPKMSpecies.Add(544, "Whirlipede")
        dPKMSpecies.Add(545, "Scolipede")
        dPKMSpecies.Add(546, "Cottonee")
        dPKMSpecies.Add(547, "Whimsicott")
        dPKMSpecies.Add(548, "Petilil")
        dPKMSpecies.Add(549, "Lilligant")
        dPKMSpecies.Add(550, "Basculin")
        dPKMSpecies.Add(551, "Sandile")
        dPKMSpecies.Add(552, "Krokorok")
        dPKMSpecies.Add(553, "Krookodile")
        dPKMSpecies.Add(554, "Darumaka")
        dPKMSpecies.Add(555, "Darmanitan")
        dPKMSpecies.Add(556, "Maractus")
        dPKMSpecies.Add(557, "Dwebble")
        dPKMSpecies.Add(558, "Crustle")
        dPKMSpecies.Add(559, "Scraggy")
        dPKMSpecies.Add(560, "Scrafty")
        dPKMSpecies.Add(561, "Sigilyph")
        dPKMSpecies.Add(562, "Yamask")
        dPKMSpecies.Add(563, "Cofagrigus")
        dPKMSpecies.Add(564, "Tirtouga")
        dPKMSpecies.Add(565, "Carracosta")
        dPKMSpecies.Add(566, "Archen")
        dPKMSpecies.Add(567, "Archeops")
        dPKMSpecies.Add(568, "Trubbish")
        dPKMSpecies.Add(569, "Garbodor")
        dPKMSpecies.Add(570, "Zorua")
        dPKMSpecies.Add(571, "Zoroark")
        dPKMSpecies.Add(572, "Minccino")
        dPKMSpecies.Add(573, "Cinccino")
        dPKMSpecies.Add(574, "Gothita")
        dPKMSpecies.Add(575, "Gothorita")
        dPKMSpecies.Add(576, "Gothitelle")
        dPKMSpecies.Add(577, "Solosis")
        dPKMSpecies.Add(578, "Duosion")
        dPKMSpecies.Add(579, "Reuniclus")
        dPKMSpecies.Add(580, "Ducklett")
        dPKMSpecies.Add(581, "Swanna")
        dPKMSpecies.Add(582, "Vanillite")
        dPKMSpecies.Add(583, "Vanillish")
        dPKMSpecies.Add(584, "Vanilluxe")
        dPKMSpecies.Add(585, "Deerling")
        dPKMSpecies.Add(586, "Sawsbuck")
        dPKMSpecies.Add(587, "Emolga")
        dPKMSpecies.Add(588, "Karrablast")
        dPKMSpecies.Add(589, "Escavalier")
        dPKMSpecies.Add(590, "Foongus")
        dPKMSpecies.Add(591, "Amoonguss")
        dPKMSpecies.Add(592, "Frillish")
        dPKMSpecies.Add(593, "Jellicent")
        dPKMSpecies.Add(594, "Alomomola")
        dPKMSpecies.Add(595, "Joltik")
        dPKMSpecies.Add(596, "Galvantula")
        dPKMSpecies.Add(597, "Ferroseed")
        dPKMSpecies.Add(598, "Ferrothorn")
        dPKMSpecies.Add(599, "Klink")
        dPKMSpecies.Add(600, "Klang")
        dPKMSpecies.Add(601, "Klinklang")
        dPKMSpecies.Add(602, "Tynamo")
        dPKMSpecies.Add(603, "Eelektrik")
        dPKMSpecies.Add(604, "Eelektross")
        dPKMSpecies.Add(605, "Elgyem")
        dPKMSpecies.Add(606, "Beheeyem")
        dPKMSpecies.Add(607, "Litwick")
        dPKMSpecies.Add(608, "Lampent")
        dPKMSpecies.Add(609, "Chandelure")
        dPKMSpecies.Add(610, "Axew")
        dPKMSpecies.Add(611, "Fraxure")
        dPKMSpecies.Add(612, "Haxorus")
        dPKMSpecies.Add(613, "Cubchoo")
        dPKMSpecies.Add(614, "Beartic")
        dPKMSpecies.Add(615, "Cryogonal")
        dPKMSpecies.Add(616, "Shelmet")
        dPKMSpecies.Add(617, "Accelgor")
        dPKMSpecies.Add(618, "Stunfisk")
        dPKMSpecies.Add(619, "Mienfoo")
        dPKMSpecies.Add(620, "Mienshao")
        dPKMSpecies.Add(621, "Druddigon")
        dPKMSpecies.Add(622, "Golett")
        dPKMSpecies.Add(623, "Golurk")
        dPKMSpecies.Add(624, "Pawniard")
        dPKMSpecies.Add(625, "Bisharp")
        dPKMSpecies.Add(626, "Bouffalant")
        dPKMSpecies.Add(627, "Rufflet")
        dPKMSpecies.Add(628, "Braviary")
        dPKMSpecies.Add(629, "Vullaby")
        dPKMSpecies.Add(630, "Mandibuzz")
        dPKMSpecies.Add(631, "Heatmor")
        dPKMSpecies.Add(632, "Durant")
        dPKMSpecies.Add(633, "Deino")
        dPKMSpecies.Add(634, "Zweilous")
        dPKMSpecies.Add(635, "Hydreigon")
        dPKMSpecies.Add(636, "Larvesta")
        dPKMSpecies.Add(637, "Volcarona")
        dPKMSpecies.Add(638, "Cobalion")
        dPKMSpecies.Add(639, "Terrakion")
        dPKMSpecies.Add(640, "Virizion")
        dPKMSpecies.Add(641, "Tornadus")
        dPKMSpecies.Add(642, "Thundurus")
        dPKMSpecies.Add(643, "Reshiram")
        dPKMSpecies.Add(644, "Zekrom")
        dPKMSpecies.Add(645, "Landorus")
        dPKMSpecies.Add(646, "Kyurem")
        dPKMSpecies.Add(647, "Keldeo")
        dPKMSpecies.Add(648, "Meloetta")
        dPKMSpecies.Add(649, "Genesect")

        With PicLibrary
            .Add(0, My.Resources._0)
            .Add(1, My.Resources._1)
            .Add(2, My.Resources._2)
            .Add(3, My.Resources._3)
            .Add(4, My.Resources._4)
            .Add(5, My.Resources._5)
            .Add(6, My.Resources._6)
            .Add(7, My.Resources._7)
            .Add(8, My.Resources._8)
            .Add(9, My.Resources._9)
            .Add(10, My.Resources._10)
            .Add(11, My.Resources._11)
            .Add(12, My.Resources._12)
            .Add(13, My.Resources._13)
            .Add(14, My.Resources._14)
            .Add(15, My.Resources._15)
            .Add(16, My.Resources._16)
            .Add(17, My.Resources._17)
            .Add(18, My.Resources._18)
            .Add(19, My.Resources._19)
            .Add(20, My.Resources._20)
            .Add(21, My.Resources._21)
            .Add(22, My.Resources._22)
            .Add(23, My.Resources._23)
            .Add(24, My.Resources._24)
            .Add(25, My.Resources._25)
            .Add(26, My.Resources._26)
            .Add(27, My.Resources._27)
            .Add(28, My.Resources._28)
            .Add(29, My.Resources._29)
            .Add(30, My.Resources._30)
            .Add(31, My.Resources._31)
            .Add(32, My.Resources._32)
            .Add(33, My.Resources._33)
            .Add(34, My.Resources._34)
            .Add(35, My.Resources._35)
            .Add(36, My.Resources._36)
            .Add(37, My.Resources._37)
            .Add(38, My.Resources._38)
            .Add(39, My.Resources._39)
            .Add(40, My.Resources._40)
            .Add(41, My.Resources._41)
            .Add(42, My.Resources._42)
            .Add(43, My.Resources._43)
            .Add(44, My.Resources._44)
            .Add(45, My.Resources._45)
            .Add(46, My.Resources._46)
            .Add(47, My.Resources._47)
            .Add(48, My.Resources._48)
            .Add(49, My.Resources._49)
            .Add(50, My.Resources._50)
            .Add(51, My.Resources._51)
            .Add(52, My.Resources._52)
            .Add(53, My.Resources._53)
            .Add(54, My.Resources._54)
            .Add(55, My.Resources._55)
            .Add(56, My.Resources._56)
            .Add(57, My.Resources._57)
            .Add(58, My.Resources._58)
            .Add(59, My.Resources._59)
            .Add(60, My.Resources._60)
            .Add(61, My.Resources._61)
            .Add(62, My.Resources._62)
            .Add(63, My.Resources._63)
            .Add(64, My.Resources._64)
            .Add(65, My.Resources._65)
            .Add(66, My.Resources._66)
            .Add(67, My.Resources._67)
            .Add(68, My.Resources._68)
            .Add(69, My.Resources._69)
            .Add(70, My.Resources._70)
            .Add(71, My.Resources._71)
            .Add(72, My.Resources._72)
            .Add(73, My.Resources._73)
            .Add(74, My.Resources._74)
            .Add(75, My.Resources._75)
            .Add(76, My.Resources._76)
            .Add(77, My.Resources._77)
            .Add(78, My.Resources._78)
            .Add(79, My.Resources._79)
            .Add(80, My.Resources._80)
            .Add(81, My.Resources._81)
            .Add(82, My.Resources._82)
            .Add(83, My.Resources._83)
            .Add(84, My.Resources._84)
            .Add(85, My.Resources._85)
            .Add(86, My.Resources._86)
            .Add(87, My.Resources._87)
            .Add(88, My.Resources._88)
            .Add(89, My.Resources._89)
            .Add(90, My.Resources._90)
            .Add(91, My.Resources._91)
            .Add(92, My.Resources._92)
            .Add(93, My.Resources._93)
            .Add(94, My.Resources._94)
            .Add(95, My.Resources._95)
            .Add(96, My.Resources._96)
            .Add(97, My.Resources._97)
            .Add(98, My.Resources._98)
            .Add(99, My.Resources._99)
            .Add(100, My.Resources._100)
            .Add(101, My.Resources._101)
            .Add(102, My.Resources._102)
            .Add(103, My.Resources._103)
            .Add(104, My.Resources._104)
            .Add(105, My.Resources._105)
            .Add(106, My.Resources._106)
            .Add(107, My.Resources._107)
            .Add(108, My.Resources._108)
            .Add(109, My.Resources._109)
            .Add(110, My.Resources._110)
            .Add(111, My.Resources._111)
            .Add(112, My.Resources._112)
            .Add(113, My.Resources._113)
            .Add(114, My.Resources._114)
            .Add(115, My.Resources._115)
            .Add(116, My.Resources._116)
            .Add(117, My.Resources._117)
            .Add(118, My.Resources._118)
            .Add(119, My.Resources._119)
            .Add(120, My.Resources._120)
            .Add(121, My.Resources._121)
            .Add(122, My.Resources._122)
            .Add(123, My.Resources._123)
            .Add(124, My.Resources._124)
            .Add(125, My.Resources._125)
            .Add(126, My.Resources._126)
            .Add(127, My.Resources._127)
            .Add(128, My.Resources._128)
            .Add(129, My.Resources._129)
            .Add(130, My.Resources._130)
            .Add(131, My.Resources._131)
            .Add(132, My.Resources._132)
            .Add(133, My.Resources._133)
            .Add(134, My.Resources._134)
            .Add(135, My.Resources._135)
            .Add(136, My.Resources._136)
            .Add(137, My.Resources._137)
            .Add(138, My.Resources._138)
            .Add(139, My.Resources._139)
            .Add(140, My.Resources._140)
            .Add(141, My.Resources._141)
            .Add(142, My.Resources._142)
            .Add(143, My.Resources._143)
            .Add(144, My.Resources._144)
            .Add(145, My.Resources._145)
            .Add(146, My.Resources._146)
            .Add(147, My.Resources._147)
            .Add(148, My.Resources._148)
            .Add(149, My.Resources._149)
            .Add(150, My.Resources._150)
            .Add(151, My.Resources._151)
            .Add(152, My.Resources._152)
            .Add(153, My.Resources._153)
            .Add(154, My.Resources._154)
            .Add(155, My.Resources._155)
            .Add(156, My.Resources._156)
            .Add(157, My.Resources._157)
            .Add(158, My.Resources._158)
            .Add(159, My.Resources._159)
            .Add(160, My.Resources._160)
            .Add(161, My.Resources._161)
            .Add(162, My.Resources._162)
            .Add(163, My.Resources._163)
            .Add(164, My.Resources._164)
            .Add(165, My.Resources._165)
            .Add(166, My.Resources._166)
            .Add(167, My.Resources._167)
            .Add(168, My.Resources._168)
            .Add(169, My.Resources._169)
            .Add(170, My.Resources._170)
            .Add(171, My.Resources._171)
            .Add(172, My.Resources._172)
            .Add(173, My.Resources._173)
            .Add(174, My.Resources._174)
            .Add(175, My.Resources._175)
            .Add(176, My.Resources._176)
            .Add(177, My.Resources._177)
            .Add(178, My.Resources._178)
            .Add(179, My.Resources._179)
            .Add(180, My.Resources._180)
            .Add(181, My.Resources._181)
            .Add(182, My.Resources._182)
            .Add(183, My.Resources._183)
            .Add(184, My.Resources._184)
            .Add(185, My.Resources._185)
            .Add(186, My.Resources._186)
            .Add(187, My.Resources._187)
            .Add(188, My.Resources._188)
            .Add(189, My.Resources._189)
            .Add(190, My.Resources._190)
            .Add(191, My.Resources._191)
            .Add(192, My.Resources._192)
            .Add(193, My.Resources._193)
            .Add(194, My.Resources._194)
            .Add(195, My.Resources._195)
            .Add(196, My.Resources._196)
            .Add(197, My.Resources._197)
            .Add(198, My.Resources._198)
            .Add(199, My.Resources._199)
            .Add(200, My.Resources._200)
            .Add(201, My.Resources._201)
            .Add(202, My.Resources._202)
            .Add(203, My.Resources._203)
            .Add(204, My.Resources._204)
            .Add(205, My.Resources._205)
            .Add(206, My.Resources._206)
            .Add(207, My.Resources._207)
            .Add(208, My.Resources._208)
            .Add(209, My.Resources._209)
            .Add(210, My.Resources._210)
            .Add(211, My.Resources._211)
            .Add(212, My.Resources._212)
            .Add(213, My.Resources._213)
            .Add(214, My.Resources._214)
            .Add(215, My.Resources._215)
            .Add(216, My.Resources._216)
            .Add(217, My.Resources._217)
            .Add(218, My.Resources._218)
            .Add(219, My.Resources._219)
            .Add(220, My.Resources._220)
            .Add(221, My.Resources._221)
            .Add(222, My.Resources._222)
            .Add(223, My.Resources._223)
            .Add(224, My.Resources._224)
            .Add(225, My.Resources._225)
            .Add(226, My.Resources._226)
            .Add(227, My.Resources._227)
            .Add(228, My.Resources._228)
            .Add(229, My.Resources._229)
            .Add(230, My.Resources._230)
            .Add(231, My.Resources._231)
            .Add(232, My.Resources._232)
            .Add(233, My.Resources._233)
            .Add(234, My.Resources._234)
            .Add(235, My.Resources._235)
            .Add(236, My.Resources._236)
            .Add(237, My.Resources._237)
            .Add(238, My.Resources._238)
            .Add(239, My.Resources._239)
            .Add(240, My.Resources._240)
            .Add(241, My.Resources._241)
            .Add(242, My.Resources._242)
            .Add(243, My.Resources._243)
            .Add(244, My.Resources._244)
            .Add(245, My.Resources._245)
            .Add(246, My.Resources._246)
            .Add(247, My.Resources._247)
            .Add(248, My.Resources._248)
            .Add(249, My.Resources._249)
            .Add(250, My.Resources._250)
            .Add(251, My.Resources._251)
            .Add(252, My.Resources._252)
            .Add(253, My.Resources._253)
            .Add(254, My.Resources._254)
            .Add(255, My.Resources._255)
            .Add(256, My.Resources._256)
            .Add(257, My.Resources._257)
            .Add(258, My.Resources._258)
            .Add(259, My.Resources._259)
            .Add(260, My.Resources._260)
            .Add(261, My.Resources._261)
            .Add(262, My.Resources._262)
            .Add(263, My.Resources._263)
            .Add(264, My.Resources._264)
            .Add(265, My.Resources._265)
            .Add(266, My.Resources._266)
            .Add(267, My.Resources._267)
            .Add(268, My.Resources._268)
            .Add(269, My.Resources._269)
            .Add(270, My.Resources._270)
            .Add(271, My.Resources._271)
            .Add(272, My.Resources._272)
            .Add(273, My.Resources._273)
            .Add(274, My.Resources._274)
            .Add(275, My.Resources._275)
            .Add(276, My.Resources._276)
            .Add(277, My.Resources._277)
            .Add(278, My.Resources._278)
            .Add(279, My.Resources._279)
            .Add(280, My.Resources._280)
            .Add(281, My.Resources._281)
            .Add(282, My.Resources._282)
            .Add(283, My.Resources._283)
            .Add(284, My.Resources._284)
            .Add(285, My.Resources._285)
            .Add(286, My.Resources._286)
            .Add(287, My.Resources._287)
            .Add(288, My.Resources._288)
            .Add(289, My.Resources._289)
            .Add(290, My.Resources._290)
            .Add(291, My.Resources._291)
            .Add(292, My.Resources._292)
            .Add(293, My.Resources._293)
            .Add(294, My.Resources._294)
            .Add(295, My.Resources._295)
            .Add(296, My.Resources._296)
            .Add(297, My.Resources._297)
            .Add(298, My.Resources._298)
            .Add(299, My.Resources._299)
            .Add(300, My.Resources._300)
            .Add(301, My.Resources._301)
            .Add(302, My.Resources._302)
            .Add(303, My.Resources._303)
            .Add(304, My.Resources._304)
            .Add(305, My.Resources._305)
            .Add(306, My.Resources._306)
            .Add(307, My.Resources._307)
            .Add(308, My.Resources._308)
            .Add(309, My.Resources._309)
            .Add(310, My.Resources._310)
            .Add(311, My.Resources._311)
            .Add(312, My.Resources._312)
            .Add(313, My.Resources._313)
            .Add(314, My.Resources._314)
            .Add(315, My.Resources._315)
            .Add(316, My.Resources._316)
            .Add(317, My.Resources._317)
            .Add(318, My.Resources._318)
            .Add(319, My.Resources._319)
            .Add(320, My.Resources._320)
            .Add(321, My.Resources._321)
            .Add(322, My.Resources._322)
            .Add(323, My.Resources._323)
            .Add(324, My.Resources._324)
            .Add(325, My.Resources._325)
            .Add(326, My.Resources._326)
            .Add(327, My.Resources._327)
            .Add(328, My.Resources._328)
            .Add(329, My.Resources._329)
            .Add(330, My.Resources._330)
            .Add(331, My.Resources._331)
            .Add(332, My.Resources._332)
            .Add(333, My.Resources._333)
            .Add(334, My.Resources._334)
            .Add(335, My.Resources._335)
            .Add(336, My.Resources._336)
            .Add(337, My.Resources._337)
            .Add(338, My.Resources._338)
            .Add(339, My.Resources._339)
            .Add(340, My.Resources._340)
            .Add(341, My.Resources._341)
            .Add(342, My.Resources._342)
            .Add(343, My.Resources._343)
            .Add(344, My.Resources._344)
            .Add(345, My.Resources._345)
            .Add(346, My.Resources._346)
            .Add(347, My.Resources._347)
            .Add(348, My.Resources._348)
            .Add(349, My.Resources._349)
            .Add(350, My.Resources._350)
            .Add(351, My.Resources._351)
            .Add(352, My.Resources._352)
            .Add(353, My.Resources._353)
            .Add(354, My.Resources._354)
            .Add(355, My.Resources._355)
            .Add(356, My.Resources._356)
            .Add(357, My.Resources._357)
            .Add(358, My.Resources._358)
            .Add(359, My.Resources._359)
            .Add(360, My.Resources._360)
            .Add(361, My.Resources._361)
            .Add(362, My.Resources._362)
            .Add(363, My.Resources._363)
            .Add(364, My.Resources._364)
            .Add(365, My.Resources._365)
            .Add(366, My.Resources._366)
            .Add(367, My.Resources._367)
            .Add(368, My.Resources._368)
            .Add(369, My.Resources._369)
            .Add(370, My.Resources._370)
            .Add(371, My.Resources._371)
            .Add(372, My.Resources._372)
            .Add(373, My.Resources._373)
            .Add(374, My.Resources._374)
            .Add(375, My.Resources._375)
            .Add(376, My.Resources._376)
            .Add(377, My.Resources._377)
            .Add(378, My.Resources._378)
            .Add(379, My.Resources._379)
            .Add(380, My.Resources._380)
            .Add(381, My.Resources._381)
            .Add(382, My.Resources._382)
            .Add(383, My.Resources._383)
            .Add(384, My.Resources._384)
            .Add(385, My.Resources._385)
            .Add(386, My.Resources._386)
            .Add(387, My.Resources._387)
            .Add(388, My.Resources._388)
            .Add(389, My.Resources._389)
            .Add(390, My.Resources._390)
            .Add(391, My.Resources._391)
            .Add(392, My.Resources._392)
            .Add(393, My.Resources._393)
            .Add(394, My.Resources._394)
            .Add(395, My.Resources._395)
            .Add(396, My.Resources._396)
            .Add(397, My.Resources._397)
            .Add(398, My.Resources._398)
            .Add(399, My.Resources._399)
            .Add(400, My.Resources._400)
            .Add(401, My.Resources._401)
            .Add(402, My.Resources._402)
            .Add(403, My.Resources._403)
            .Add(404, My.Resources._404)
            .Add(405, My.Resources._405)
            .Add(406, My.Resources._406)
            .Add(407, My.Resources._407)
            .Add(408, My.Resources._408)
            .Add(409, My.Resources._409)
            .Add(410, My.Resources._410)
            .Add(411, My.Resources._411)
            .Add(412, My.Resources._412)
            .Add(413, My.Resources._413)
            .Add(414, My.Resources._414)
            .Add(415, My.Resources._415)
            .Add(416, My.Resources._416)
            .Add(417, My.Resources._417)
            .Add(418, My.Resources._418)
            .Add(419, My.Resources._419)
            .Add(420, My.Resources._420)
            .Add(421, My.Resources._421)
            .Add(422, My.Resources._422)
            .Add(423, My.Resources._423)
            .Add(424, My.Resources._424)
            .Add(425, My.Resources._425)
            .Add(426, My.Resources._426)
            .Add(427, My.Resources._427)
            .Add(428, My.Resources._428)
            .Add(429, My.Resources._429)
            .Add(430, My.Resources._430)
            .Add(431, My.Resources._431)
            .Add(432, My.Resources._432)
            .Add(433, My.Resources._433)
            .Add(434, My.Resources._434)
            .Add(435, My.Resources._435)
            .Add(436, My.Resources._436)
            .Add(437, My.Resources._437)
            .Add(438, My.Resources._438)
            .Add(439, My.Resources._439)
            .Add(440, My.Resources._440)
            .Add(441, My.Resources._441)
            .Add(442, My.Resources._442)
            .Add(443, My.Resources._443)
            .Add(444, My.Resources._444)
            .Add(445, My.Resources._445)
            .Add(446, My.Resources._446)
            .Add(447, My.Resources._447)
            .Add(448, My.Resources._448)
            .Add(449, My.Resources._449)
            .Add(450, My.Resources._450)
            .Add(451, My.Resources._451)
            .Add(452, My.Resources._452)
            .Add(453, My.Resources._453)
            .Add(454, My.Resources._454)
            .Add(455, My.Resources._455)
            .Add(456, My.Resources._456)
            .Add(457, My.Resources._457)
            .Add(458, My.Resources._458)
            .Add(459, My.Resources._459)
            .Add(460, My.Resources._460)
            .Add(461, My.Resources._461)
            .Add(462, My.Resources._462)
            .Add(463, My.Resources._463)
            .Add(464, My.Resources._464)
            .Add(465, My.Resources._465)
            .Add(466, My.Resources._466)
            .Add(467, My.Resources._467)
            .Add(468, My.Resources._468)
            .Add(469, My.Resources._469)
            .Add(470, My.Resources._470)
            .Add(471, My.Resources._471)
            .Add(472, My.Resources._472)
            .Add(473, My.Resources._473)
            .Add(474, My.Resources._474)
            .Add(475, My.Resources._475)
            .Add(476, My.Resources._476)
            .Add(477, My.Resources._477)
            .Add(478, My.Resources._478)
            .Add(479, My.Resources._479)
            .Add(480, My.Resources._480)
            .Add(481, My.Resources._481)
            .Add(482, My.Resources._482)
            .Add(483, My.Resources._483)
            .Add(484, My.Resources._484)
            .Add(485, My.Resources._485)
            .Add(486, My.Resources._486)
            .Add(487, My.Resources._487_altered)
            .Add(488, My.Resources._488)
            .Add(489, My.Resources._489)
            .Add(490, My.Resources._490)
            .Add(491, My.Resources._491)
            .Add(492, My.Resources._492_land)
            .Add(493, My.Resources._493_normal)
            .Add(494, My.Resources._494)
            .Add(495, My.Resources._495)
            .Add(496, My.Resources._496)
            .Add(497, My.Resources._497)
            .Add(498, My.Resources._498)
            .Add(499, My.Resources._499)
            .Add(500, My.Resources._500)
            .Add(501, My.Resources._501)
            .Add(502, My.Resources._502)
            .Add(503, My.Resources._503)
            .Add(504, My.Resources._504)
            .Add(505, My.Resources._505)
            .Add(506, My.Resources._506)
            .Add(507, My.Resources._507)
            .Add(508, My.Resources._508)
            .Add(509, My.Resources._509)
            .Add(510, My.Resources._510)
            .Add(511, My.Resources._511)
            .Add(512, My.Resources._512)
            .Add(513, My.Resources._513)
            .Add(514, My.Resources._514)
            .Add(515, My.Resources._515)
            .Add(516, My.Resources._516)
            .Add(517, My.Resources._517)
            .Add(518, My.Resources._518)
            .Add(519, My.Resources._519)
            .Add(520, My.Resources._520)
            .Add(521, My.Resources._521)
            .Add(522, My.Resources._522)
            .Add(523, My.Resources._523)
            .Add(524, My.Resources._524)
            .Add(525, My.Resources._525)
            .Add(526, My.Resources._526)
            .Add(527, My.Resources._527)
            .Add(528, My.Resources._528)
            .Add(529, My.Resources._529)
            .Add(530, My.Resources._530)
            .Add(531, My.Resources._531)
            .Add(532, My.Resources._532)
            .Add(533, My.Resources._533)
            .Add(534, My.Resources._534)
            .Add(535, My.Resources._535)
            .Add(536, My.Resources._536)
            .Add(537, My.Resources._537)
            .Add(538, My.Resources._538)
            .Add(539, My.Resources._539)
            .Add(540, My.Resources._540)
            .Add(541, My.Resources._541)
            .Add(542, My.Resources._542)
            .Add(543, My.Resources._543)
            .Add(544, My.Resources._544)
            .Add(545, My.Resources._545)
            .Add(546, My.Resources._546)
            .Add(547, My.Resources._547)
            .Add(548, My.Resources._548)
            .Add(549, My.Resources._549)
            .Add(550, My.Resources._550)
            .Add(551, My.Resources._551)
            .Add(552, My.Resources._552)
            .Add(553, My.Resources._553)
            .Add(554, My.Resources._554)
            .Add(555, My.Resources._555)
            .Add(556, My.Resources._556)
            .Add(557, My.Resources._557)
            .Add(558, My.Resources._558)
            .Add(559, My.Resources._559)
            .Add(560, My.Resources._560)
            .Add(561, My.Resources._561)
            .Add(562, My.Resources._562)
            .Add(563, My.Resources._563)
            .Add(564, My.Resources._564)
            .Add(565, My.Resources._565)
            .Add(566, My.Resources._566)
            .Add(567, My.Resources._567)
            .Add(568, My.Resources._568)
            .Add(569, My.Resources._569)
            .Add(570, My.Resources._570)
            .Add(571, My.Resources._571)
            .Add(572, My.Resources._572)
            .Add(573, My.Resources._573)
            .Add(574, My.Resources._574)
            .Add(575, My.Resources._575)
            .Add(576, My.Resources._576)
            .Add(577, My.Resources._577)
            .Add(578, My.Resources._578)
            .Add(579, My.Resources._579)
            .Add(580, My.Resources._580)
            .Add(581, My.Resources._581)
            .Add(582, My.Resources._582)
            .Add(583, My.Resources._583)
            .Add(584, My.Resources._584)
            .Add(585, My.Resources._585_autumn)
            .Add(586, My.Resources._586_autumn)
            .Add(587, My.Resources._587)
            .Add(588, My.Resources._588)
            .Add(589, My.Resources._589)
            .Add(590, My.Resources._590)
            .Add(591, My.Resources._591)
            .Add(592, My.Resources._592)
            .Add(593, My.Resources._593)
            .Add(594, My.Resources._594)
            .Add(595, My.Resources._595)
            .Add(596, My.Resources._596)
            .Add(597, My.Resources._597)
            .Add(598, My.Resources._598)
            .Add(599, My.Resources._599)
            .Add(600, My.Resources._600)
            .Add(601, My.Resources._601)
            .Add(602, My.Resources._602)
            .Add(603, My.Resources._603)
            .Add(604, My.Resources._604)
            .Add(605, My.Resources._605)
            .Add(606, My.Resources._606)
            .Add(607, My.Resources._607)
            .Add(608, My.Resources._608)
            .Add(609, My.Resources._609)
            .Add(610, My.Resources._610)
            .Add(611, My.Resources._611)
            .Add(612, My.Resources._612)
            .Add(613, My.Resources._613)
            .Add(614, My.Resources._614)
            .Add(615, My.Resources._615)
            .Add(616, My.Resources._616)
            .Add(617, My.Resources._617)
            .Add(618, My.Resources._618)
            .Add(619, My.Resources._619)
            .Add(620, My.Resources._620)
            .Add(621, My.Resources._621)
            .Add(622, My.Resources._622)
            .Add(623, My.Resources._623)
            .Add(624, My.Resources._624)
            .Add(625, My.Resources._625)
            .Add(626, My.Resources._626)
            .Add(627, My.Resources._627)
            .Add(628, My.Resources._628)
            .Add(629, My.Resources._629)
            .Add(630, My.Resources._630)
            .Add(631, My.Resources._631)
            .Add(632, My.Resources._632)
            .Add(633, My.Resources._633)
            .Add(634, My.Resources._634)
            .Add(635, My.Resources._635)
            .Add(636, My.Resources._636)
            .Add(637, My.Resources._637)
            .Add(638, My.Resources._638)
            .Add(639, My.Resources._639)
            .Add(640, My.Resources._640)
            .Add(641, My.Resources._641_incarnate)
            .Add(642, My.Resources._642_incarnate)
            .Add(643, My.Resources._643)
            .Add(644, My.Resources._644)
            .Add(645, My.Resources._645_incarnate)
            .Add(646, My.Resources._646)
            .Add(647, My.Resources._647_regular)
            .Add(648, My.Resources._648_aria)
            .Add(649, My.Resources._649)
        End With

        'Black/White Locations
        bwLocations.Add(0, "---")
        bwLocations.Add(1, "Mystery Zone")
        bwLocations.Add(2, "Faraway place")
        bwLocations.Add(3, "---")
        bwLocations.Add(4, "Nuvema Town")
        bwLocations.Add(5, "Accumula Town")
        bwLocations.Add(6, "Striaton City")
        bwLocations.Add(7, "Nacrene City")
        bwLocations.Add(8, "Castelia City")
        bwLocations.Add(9, "Nimbasa City")
        bwLocations.Add(10, "Driftveil City")
        bwLocations.Add(11, "Mistralton City")
        bwLocations.Add(12, "Icirrus City")
        bwLocations.Add(13, "Opelucid City")
        bwLocations.Add(14, "Route 1")
        bwLocations.Add(15, "Route 2")
        bwLocations.Add(16, "Route 3")
        bwLocations.Add(17, "Route 4")
        bwLocations.Add(18, "Route 5")
        bwLocations.Add(19, "Route 6")
        bwLocations.Add(20, "Route 7")
        bwLocations.Add(21, "Route 8")
        bwLocations.Add(22, "Route 9")
        bwLocations.Add(23, "Route 10")
        bwLocations.Add(24, "Route 11")
        bwLocations.Add(25, "Route 12")
        bwLocations.Add(26, "Route 13")
        bwLocations.Add(27, "Route 14")
        bwLocations.Add(28, "Route 15")
        bwLocations.Add(29, "Route 16")
        bwLocations.Add(30, "Route 17")
        bwLocations.Add(31, "Route 18")
        bwLocations.Add(32, "Dreamyard")
        bwLocations.Add(33, "Pinwheel Forest")
        bwLocations.Add(34, "Desert Resort")
        bwLocations.Add(35, "Relic Castle")
        bwLocations.Add(36, "Cold Storage")
        bwLocations.Add(37, "Chargestone Cave")
        bwLocations.Add(38, "Twist Mountain")
        bwLocations.Add(39, "Dragonspiral Tower")
        bwLocations.Add(40, "Victory Road")
        bwLocations.Add(41, "Lacunosa Town")
        bwLocations.Add(42, "Undella Town")
        bwLocations.Add(43, "Anville Town")
        bwLocations.Add(44, "Pokémon League")
        bwLocations.Add(45, "N's Castle")
        bwLocations.Add(46, "Royal Unova")
        bwLocations.Add(47, "Gear Station")
        bwLocations.Add(48, "Battle Subway")
        bwLocations.Add(49, "Musical Theater")
        bwLocations.Add(50, "Black City")
        bwLocations.Add(51, "White Forest")
        bwLocations.Add(52, "Unity Tower")
        bwLocations.Add(53, "Wellspring Cave")
        bwLocations.Add(54, "Mistralton Cave")
        bwLocations.Add(55, "Rumination Field")
        bwLocations.Add(56, "Celestial Tower")
        bwLocations.Add(57, "Moor of Icirrus")
        bwLocations.Add(58, "Shopping Mall")
        bwLocations.Add(59, "Challenger's Cave")
        bwLocations.Add(60, "Poké Transfer Lab")
        bwLocations.Add(61, "Giant Chasm")
        bwLocations.Add(62, "Liberty Garden")
        bwLocations.Add(63, "P2 Laboratory")
        bwLocations.Add(64, "Skyarrow Bridge")
        bwLocations.Add(65, "Driftveil Drawbridge")
        bwLocations.Add(66, "Tubeline Bridge")
        bwLocations.Add(67, "Village Bridge")
        bwLocations.Add(68, "Marvelous Bridge")
        bwLocations.Add(69, "Entralink")
        bwLocations.Add(70, "Abundant Shrine")
        bwLocations.Add(71, "Undella Bay")
        bwLocations.Add(72, "Lostlorn Forest")
        bwLocations.Add(73, "Trial Chamber")
        bwLocations.Add(74, "Guidance Chamber")
        bwLocations.Add(75, "Entree Forest")
        bwLocations.Add(76, "Nimbasa City")
        bwLocations.Add(77, "Driftveil City")
        bwLocations.Add(78, "Mistralton City")
        bwLocations.Add(79, "Icirrus City")
        bwLocations.Add(80, "Opelucid City")
        bwLocations.Add(81, "Nuvema Town")
        bwLocations.Add(82, "White Forest")
        bwLocations.Add(83, "Black City")
        bwLocations.Add(84, "Cold Storage")
        bwLocations.Add(85, "Chargestone Cave")
        bwLocations.Add(86, "Twist Mountain")
        bwLocations.Add(87, "Dragonspiral Tower")
        bwLocations.Add(88, "Giant Chasm")
        bwLocations.Add(89, "Driftveil Drawbridge")
        bwLocations.Add(90, "Tubeline Bridge")
        bwLocations.Add(91, "Village Bridge")
        bwLocations.Add(92, "Marvelous Bridge")
        bwLocations.Add(93, "Route 5")
        bwLocations.Add(94, "Route 6")
        bwLocations.Add(95, "Route 7")
        bwLocations.Add(96, "Route 8")
        bwLocations.Add(97, "Route 9")
        bwLocations.Add(98, "Route 11")
        bwLocations.Add(99, "Route 12")
        bwLocations.Add(100, "Route 13")
        bwLocations.Add(101, "Route 14")
        bwLocations.Add(102, "Route 15")
        bwLocations.Add(103, "Route 16")
        bwLocations.Add(104, "Lacunosa Town")
        bwLocations.Add(105, "Undella Town")
        bwLocations.Add(106, "Accumula Gate")
        bwLocations.Add(107, "Undella Gate")
        bwLocations.Add(108, "Nacrene Gate")
        bwLocations.Add(109, "Castelia Gate")
        bwLocations.Add(110, "Nimbasa Gate")
        bwLocations.Add(111, "Opelucid Gate")
        bwLocations.Add(112, "Black Gate")
        bwLocations.Add(113, "White Gate")
        bwLocations.Add(114, "Bridge Gate")
        bwLocations.Add(115, "Route Gate")
        bwLocations.Add(116, "Abyssal Ruins")
        bwLocations.Add(30000, "---")
        bwLocations.Add(30001, "PokeShifter")
        bwLocations.Add(30002, "Link Trade")
        bwLocations.Add(30003, "Link Trade")
        bwLocations.Add(30004, "Kanto")
        bwLocations.Add(30005, "Johto")
        bwLocations.Add(30006, "Hoenn")
        bwLocations.Add(30007, "Sinnoh")
        bwLocations.Add(30008, "Distant Land")
        bwLocations.Add(30009, "---")
        bwLocations.Add(30010, "Transfer Machine Celebi")
        bwLocations.Add(30011, "Celebi Event")
        bwLocations.Add(30012, "Transfer Machine Beasts")
        bwLocations.Add(30013, "Lost Forest(Crown)")
        bwLocations.Add(30014, "High Forest")
        bwLocations.Add(40000, "---")
        bwLocations.Add(40001, "Lovely place")
        bwLocations.Add(40002, "---")
        bwLocations.Add(40003, "Pokémon Movie")
        bwLocations.Add(40004, "Pokémon Movie 10")
        bwLocations.Add(40005, "Pokémon Movie 11")
        bwLocations.Add(40006, "Pokémon Movie 12")
        bwLocations.Add(40007, "Pokémon Movie 13")
        bwLocations.Add(40008, "Pokémon Movie 14")
        bwLocations.Add(40009, "Pokémon Movie 15")
        bwLocations.Add(40010, "Pokémon Movie 16")
        bwLocations.Add(40011, "Pokémon Movie 17")
        bwLocations.Add(40012, "Pokémon Movie 18")
        bwLocations.Add(40013, "Pokémon Movie 19")
        bwLocations.Add(40014, "Pokémon Movie 20")
        bwLocations.Add(40015, "Pokémon Center")
        bwLocations.Add(40016, "Pokémon Cartoon")
        bwLocations.Add(40017, "PC Tokyo")
        bwLocations.Add(40018, "PC Osaka")
        bwLocations.Add(40019, "PC Fukuoka")
        bwLocations.Add(40020, "PC Nagoya")
        bwLocations.Add(40021, "PC Sapporo")
        bwLocations.Add(40022, "PC Yokohama")
        bwLocations.Add(40023, "WCS")
        bwLocations.Add(40024, "WCS 2010")
        bwLocations.Add(40025, "WCS 2011")
        bwLocations.Add(40026, "WCS 2012")
        bwLocations.Add(40027, "WCS 2013")
        bwLocations.Add(40028, "WCS 2014")
        bwLocations.Add(40029, "WCS 2015")
        bwLocations.Add(40030, "WCS 2016")
        bwLocations.Add(40031, "WCS 2017")
        bwLocations.Add(40032, "WCS 2018")
        bwLocations.Add(40033, "WCS 2019")
        bwLocations.Add(40034, "WCS 2020")
        bwLocations.Add(40035, "Worlds")
        bwLocations.Add(40036, "Worlds 2010")
        bwLocations.Add(40037, "Worlds 2011")
        bwLocations.Add(40038, "Worlds 2012")
        bwLocations.Add(40039, "Worlds 2013")
        bwLocations.Add(40040, "Worlds 2014")
        bwLocations.Add(40041, "Worlds 2015")
        bwLocations.Add(40042, "Worlds 2016")
        bwLocations.Add(40043, "Worlds 2017")
        bwLocations.Add(40044, "Worlds 2018")
        bwLocations.Add(40045, "Worlds 2019")
        bwLocations.Add(40046, "Worlds 2020")
        bwLocations.Add(40047, "VGE")
        bwLocations.Add(40048, "VGE 2010")
        bwLocations.Add(40049, "VGE 2011")
        bwLocations.Add(40050, "VGE 2012")
        bwLocations.Add(40051, "VGE 2013")
        bwLocations.Add(40052, "VGE 2014")
        bwLocations.Add(40053, "VGE 2015")
        bwLocations.Add(40054, "VGE 2016")
        bwLocations.Add(40055, "VGE 2017")
        bwLocations.Add(40056, "VGE 2018")
        bwLocations.Add(40057, "VGE 2019")
        bwLocations.Add(40058, "VGE 2020")
        bwLocations.Add(40059, "Pokemon Event")
        bwLocations.Add(40060, "Battle Competition")
        bwLocations.Add(40061, "Game Event")
        bwLocations.Add(40062, "Pokémon Fan Club")
        bwLocations.Add(40063, "Pokémon Sunday")
        bwLocations.Add(40064, "Challenge Plaza")
        bwLocations.Add(40065, "Battle Challenge")
        bwLocations.Add(40066, "Trainers' Court")
        bwLocations.Add(40067, "Battle Tour")
        bwLocations.Add(40068, "Concert")
        bwLocations.Add(40069, "Wi-Fi Gift")
        bwLocations.Add(40070, "Pokémon Ranger")
        bwLocations.Add(40071, "Ranger Union")
        bwLocations.Add(40072, "PBR")
        bwLocations.Add(40073, "Pokémon DW")
        bwLocations.Add(40074, "Pokemon Event 10")
        bwLocations.Add(40075, "Pokemon Event 11")
        bwLocations.Add(40076, "Pokemon Event 12")
        bwLocations.Add(40077, "Pokemon Event 13")
        bwLocations.Add(40078, "Pokemon Event 14")
        bwLocations.Add(40079, "Pokemon Event 15")
        bwLocations.Add(40080, "Pokemon Event 16")
        bwLocations.Add(40081, "Pokemon Event 17")
        bwLocations.Add(40082, "Pokemon Event 18")
        bwLocations.Add(40083, "Pokemon Event 19")
        bwLocations.Add(40084, "Pokemon Event 20")
        bwLocations.Add(40085, "Pokemon Festa")
        bwLocations.Add(40086, "Pokemon Festa 10")
        bwLocations.Add(40087, "Pokemon Festa 11")
        bwLocations.Add(40088, "Pokemon Festa 12")
        bwLocations.Add(40089, "Pokemon Festa 13")
        bwLocations.Add(40090, "Pokemon Festa 14")
        bwLocations.Add(40091, "Pokemon Festa 15")
        bwLocations.Add(40092, "Pokemon Festa 16")
        bwLocations.Add(40093, "Pokemon Festa 17")
        bwLocations.Add(40094, "Pokemon Festa 18")
        bwLocations.Add(40095, "Pokemon Festa 19")
        bwLocations.Add(40096, "Pokemon Festa 20")
        bwLocations.Add(40097, "POKEPARK")
        bwLocations.Add(40098, "POKEPARK 10")
        bwLocations.Add(40099, "POKEPARK 11")
        bwLocations.Add(40100, "POKEPARK 12")
        bwLocations.Add(40101, "POKEPARK 13")
        bwLocations.Add(40102, "POKEPARK 14")
        bwLocations.Add(40103, "POKEPARK 15")
        bwLocations.Add(40104, "POKEPARK 16")
        bwLocations.Add(40105, "POKEPARK 17")
        bwLocations.Add(40106, "POKEPARK 18")
        bwLocations.Add(40107, "POKEPARK 19")
        bwLocations.Add(40108, "POKEPARK 20")
        bwLocations.Add(40109, "Event Site")
        bwLocations.Add(60000, "---")
        bwLocations.Add(60001, "Stranger")
        bwLocations.Add(60002, "Day-Care Couple")
        bwLocations.Add(60003, "Treasure Hunter")

        With hometowns
            .Add(0, "Game Recieved In")
            .Add(1, "Hoenn(Sapphrire)")

        End With

        With genders
            .Add(0, "Male")
            .Add(1, "Female")
            .Add(2, "Random/Genderless")
        End With

        With ot_genders
            .Add(0, "Male")
            .Add(1, "Female")
            .Add(3, "Recipient's Gender")
        End With

        With ctype_name
            .Add(1, "Pokemon")
            .Add(2, "(Key) Item")
            .Add(3, "Power")
        End With

        With ctype_color
            .Add(1, Color.Blue)
            .Add(2, Color.DeepPink)
            .Add(3, Color.Goldenrod)
        End With

        mDicInit = True
    End Sub
#End Region
#Region "Functions"
    Public Shared Function ReturnName(inb As UInt16) As String
        DicInit()
        Return dPKMSpecies(inb)
    End Function
    Public Shared Function ReturnSprite(inb As UInt16) As Image
        DicInit()
        Return PicLibrary(inb)
    End Function
    Public Shared Function ReturnShininess(inb As Byte) As String
        Dim out As String = "NA"
        If inb = 0 Then
            out = "Not Shiny"
        ElseIf inb = 1 Then
            out = "Can Be Shiny"
        ElseIf inb = 2 Then
            out = "Always Shiny"
        End If
        Return out
    End Function
    Public Shared Function ReturnLocation(inb As UInt16) As String
        DicInit()
        Return bwLocations(inb)
    End Function
    Public Shared Function ReturnHometown(inb As Byte) As String
        DicInit()
        Return hometowns(inb)
    End Function
    Public Shared Function ReturnGender(inb As Byte) As String
        DicInit()
        Return genders(inb)
    End Function
    Public Shared Function ReturnOTGender(inb As Byte) As String
        DicInit()
        Return ot_genders(inb)
    End Function
    Public Shared Function ReturnCTypeName(inb As Byte) As String
        DicInit()
        Return ctype_name(inb)
    End Function
    Public Shared Function ReturnCTypeColor(inb As Byte) As Color
        DicInit()
        Return ctype_color(inb)
    End Function
#End Region
End Class
#End Region
